/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiIntakeRouteImport } from './routes/api/intake'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntakeRoute = ApiIntakeRouteImport.update({
  id: '/api/intake',
  path: '/api/intake',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRoute
  '/practice': typeof PracticeRoute
  '/report': typeof ReportRoute
  '/api/intake': typeof ApiIntakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRoute
  '/practice': typeof PracticeRoute
  '/report': typeof ReportRoute
  '/api/intake': typeof ApiIntakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/knowledge': typeof KnowledgeRoute
  '/practice': typeof PracticeRoute
  '/report': typeof ReportRoute
  '/api/intake': typeof ApiIntakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/knowledge' | '/practice' | '/report' | '/api/intake'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/knowledge' | '/practice' | '/report' | '/api/intake'
  id: '__root__' | '/' | '/knowledge' | '/practice' | '/report' | '/api/intake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PracticeRoute: typeof PracticeRoute
  ReportRoute: typeof ReportRoute
  ApiIntakeRoute: typeof ApiIntakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intake': {
      id: '/api/intake'
      path: '/api/intake'
      fullPath: '/api/intake'
      preLoaderRoute: typeof ApiIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeRoute: KnowledgeRoute,
  PracticeRoute: PracticeRoute,
  ReportRoute: ReportRoute,
  ApiIntakeRoute: ApiIntakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
